export const mockSaunas = [
  {
    id: "cl5krnvob0160xgudyiep2r1p",
    name: "Saunakatamaraani",
    url_name: "saunakatamaraani",
    location: "Näsijärvi",
    capacity: 12,
    pricemin: 400,
    pricemax: 450,
    equipment: ["Jääkaappi", "WC", "Äänentoisto", "Grilli", "Kattoterassi"],
    images: ["public\\images\\saunakatamaraani.jpg"],
    mainImage: "saunakatamaraani.jpg",
    email: "kippari@suomenkatamaraani.fi",
    phone: "+358408317705",
    url: "https://suomenkatamaraani.fi/saunakatamaraani/",
    notes: "",
  },
  {
    id: "cl5kqndgz0041xgudmso68l8t",
    name: "M/S Suvanto",
    url_name: "ms-suvanto",
    location: "Pyhäjärvi",
    capacity: 12,
    pricemin: 500,
    pricemax: 500,
    equipment: [
      "Suihku",
      "WC",
      "Pukuhuone",
      "Poreallas",
      "Äänentoisto",
      "Grilli",
      "Jääkaappi",
      "Kahvinkeitin",
      "Jääpalakone",
      "Takka",
      "Kattoterassi",
    ],
    images: ["public\\images\\ms_suvanto_1.jpg"],
    mainImage: "ms_suvanto_1.jpg",
    email: "jukka.oksala7@gmail.com",
    phone: "+358405888859",
    url: "http://www.lauttasauna.fi/434798059",
    notes: "",
  },
]
